name: Build

on:
  release:
    types: [published]

  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build
      run: |
        ls -la
        ./build-mipsel.sh

