name: Build

on:
  release:
    types: [published]

  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    # ubuntu-22.04 is needed for older libffi.
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build
      run: |
        ls -la
        ./build-mipsel.sh

