name: Build

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # ubuntu-22.04 is needed for older libffi.
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build Micropython (MIPSEL Static) and Extract Versions
      id: build_and_extract
      run: |
        ./build-mipsel.sh

    - name: Upload Micropython Artifact with Version and Arch
      uses: actions/upload-artifact@v4
      with:
        name: micropython-${{ env.micropython_arch }}-${{ env.micropython_version }}
        path: build/micropython-*

    - name: Upload mpy-cross Artifact with Version and Arch
      uses: actions/upload-artifact@v4
      with:
        name: mpy-cross-${{ env.mpycross_arch }}-${{ env.mpycross_version }}
        path: build/mpy-cross-*

    outputs:
      micropython_version: ${{ env.micropython_version }}
      micropython_arch: ${{ env.micropython_arch }}
      mpycross_version: ${{ env.mpycross_version }}
      mpycross_arch: ${{ env.mpycross_arch }}